version: '3.1'
services:
  # nginx:
  mysql:
    container_name: bookstore-database
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    expose:
      - '3306'
  api:
    container_name: bookstore-api
    image: alexandrelamberty/bookstore-api:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      API_PORT: ${API_PORT}
      DB_PORT: ${DB_PORT}
      DB_SERVER: ${DB_SERVER}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    volumes:
      - media_data:/usr/src/app/public
    depends_on:
      - mysql
  web:
    container_name: bookstore-web-app
    image: alexandrelamberty/bookstore-web-app:latest
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api

volumes:
  media_data:

